name: Java 17 to 21 Transformation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven (Java 17)
      run: mvn clean install

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  

    - name: Run Amazon Q Code Transformation
      run: |
        # Install the AWS CLI
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

        # Run Amazon Q Code Transformation
        aws q code-transform start-job \
          --job-type JAVA17_TO_JAVA21 \
          --source-directory ./ \
          --output-directory ./transformed \
          --job-name "Java17to21Transformation"

    - name: Build with Maven (Java 21)
      run: |
        cd transformed
        mvn clean install
